# Generated by Django 5.0.6 on 2024-06-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acconts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
